# Generated by Django 4.1.3 on 2022-11-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
