# Generated by Django 4.1.3 on 2022-11-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Askme_app', '0005_alter_answer_user_alter_question_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(13), to='Askme_app.profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Askme_app.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(13), to='Askme_app.profile'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_positive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Askme_app.profile'),
        ),
    ]
