# Generated by Django 4.1.3 on 2022-11-16 18:57

import Askme_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askme_app', '0006_alter_answer_user_alter_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/no-avatar.jpg', upload_to=Askme_app.models.user_directory_path),
        ),
    ]
